### ISSUE TITLE
Ability to add volunteer directly to a booth

### ISSUE THREAD

**Issue by anandology** [anandology/cleansweep#50]
Right now place must be selected from an autocomplete to add a volunteer. It becomes very difficult to pick the right polling booth. It would be better to drop that and add a dropdown of all booths.

**Comment by charanjeetaap** [comment]
Need to give both the options. sometimes people don't know their booth but know the locality and polling station they go to.

**Comment by charanjeetaap** [comment]
Also we might have to add volunteers without the location but only contact number.

**Comment by anandology** [comment]
@charanjeetaap adding without location is handled in #52.

**Comment by anandology** [comment]
Fixed in 1d565aa33512e4279d1eb1bcec50d3bd3cf5c861. 

Identifying booth by locality is removed for now. Will create another issue for that.
