### ISSUE TITLE
Ability to add volunteers without linking to a booth

### ISSUE THREAD

**Issue by anandology** [anandology/cleansweep#52]
We may have to add volunteers without know their exact booth. 

This is tricky because it can potentially make the volunteer data incomplete and unusable. 

Need more thoughts on this.

**Comment by charanjeetaap** [comment]
We can think of it as adding a volunteer to a constituency or district or ward, at whatevr level they are being added. They later on push for further info of booth etc. when they login.

**Comment by anandology** [comment]
Can I assume that they'll have an email address so that they can login to the system?

**Comment by charanjeetaap** [comment]
Yes, we will not provide login without an email id.

Charanjeet Singh
AAP IT team
+91-8588833533

**Comment by charanjeetaap** [comment]
Ofcourse there will be volunteers in the system with only contact number(which will be the only mandatory value). But we will not provide a login to a volunteer untill they fill an email id in their profile.

**Comment by anandology** [comment]
On Thu, Jul 9, 2015 at 1:07 PM, charanjeetaap <notifications@github.com>
wrote:

> Ofcourse there will be volunteers in the system with only contact
> number(which will be the only mandatory value). But we will not provide a
> login to a volunteer untill they fill an email id in their profile.
>
So there are two cases here.

1. The records with email address. We'll invite them to login and ask for
booth details on first login.
2. The records with only a phone number. There is no way to ask them for
booth details. How are we going to fix this?

**Comment by charanjeetaap** [comment]
Actually initially all the data entry will be done by the people with login. When evr they will need to provide login access to a volunteer at any level, they should be forced to add the email id of that particular volunteer.

**Comment by devilankur18** [comment]
@anandology how this one is different from the #57

**Comment by anandology** [comment]
@devilankur18 yes, this is duplicate of #57. closing this.
