### ISSUE TITLE
voterlib lookup not working for Delhi

### ISSUE THREAD

**Issue by anandology** [anandology/cleansweep#53]
Thanks @RaghavPro for reporting.

**Comment by RaghavPro** [comment]
Still not fixed.
Tried with another voter id number but same error.

**Comment by anandology** [comment]
Did you `git pull`?



On Thu, Jul 9, 2015 at 8:45 PM, Raghav Sharma <notifications@github.com>
wrote:

> Still not fixed.
> Tried with another voter id number but same error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anandology/cleansweep/issues/53#issuecomment-120028263>
> .
>



-- 
Anand
http://anandology.com/

**Comment by RaghavPro** [comment]
Yes.
Try voter id: ZSX1784840

**Comment by anandology** [comment]
worked for me.

On Thu, Jul 9, 2015 at 9:29 PM, Raghav Sharma <notifications@github.com>
wrote:

> Yes.
> Try voter id: ZSX1784840
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anandology/cleansweep/issues/53#issuecomment-120048744>
> .
>



-- 
Anand
http://anandology.com/

**Comment by RaghavPro** [comment]
Weird.

My repo is up to date.
I did `python run.py` and tried signing up through Facebook.
Entered that same voter id but get an 'Invalid voter id' error.

I'll try debugging.

**Comment by anandology** [comment]
Try creating a file `production.cfg` with the following.

    VOTERDB_URL = "http://voter.missionvistaar.in/"

That should fix this.

On Thu, Jul 9, 2015 at 10:37 PM, Raghav Sharma <notifications@github.com>
wrote:

> Weird.
>
> My repo is up to date.
> I did python run.py and tried signing up through Facebook.
> Entered that same voter id but get an 'Invalid voter id' error.
>
> I'll try debugging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anandology/cleansweep/issues/53#issuecomment-120073364>
> .
>



-- 
Anand
http://anandology.com/
