### ISSUE TITLE
Option to download volunteers at a location

### ISSUE THREAD

**Issue by anandology** [anandology/cleansweep#62]

**Comment by devilankur18** [comment]
@anandology Any description about the downloaded file format, is csv ok ?

**Comment by anandology** [comment]
Excel is preferred. We can use [tablib][1] library for that.

[1]: http://docs.python-tablib.org/en/latest/

See similar from V1 of this project.
https://github.com/anandology/voternet/blob/master/voternet/webapp.py#L347

(voternet is the v1 of this project. This version is complete rewrite of that)

**Comment by devilankur18** [comment]
@anandology Please review the pull request #69

**Comment by charanjeetaap** [comment]
this download is required of only the volunteers that are in the heirarchy at some level and part of some committee. Not the general volunteers at the ground level.

**Comment by anandology** [comment]
Fixed.

**Comment by charanjeetaap** [comment]
right now its downloading all the volunteers, it need it to download only the designated volunteers i.e. the volunteers that are attached in the heirarchy at some place, like downloading all the booth incharges or polling station incharges or ward incharges/treasurer/observer etc...like that

**Comment by anandology** [comment]
@charanjeetaap that'll be a different feature. Probably exposed on the
committees page. Let this be download-all-the-volunteers.

On Fri, Jul 24, 2015 at 12:41 PM, charanjeetaap <notifications@github.com>
wrote:

> this download is required of only the volunteers that are in the heirarchy
> at some level and part of some committee. Not the general volunteers at the
> ground level.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anandology/cleansweep/issues/62#issuecomment-124379476>
> .
>



-- 
Anand
http://anandology.com/

**Comment by charanjeetaap** [comment]
but this i don't want to give to anybody, except may be the state admin

**Comment by anandology** [comment]
Every coordinator will be able to download all the volunteers at his location. Don't we need that?

**Comment by charanjeetaap** [comment]
actually the people with no designation, will be pretty large in number once we put our central data into this system, so i don't want to give the facility to download this data at all the levels except only at the state level. but instead our requirement is to give option to download data of volunteers with designation to the people at all the levels. ofcourse one will be able to download data of people only below his level

**Comment by charanjeetaap** [comment]
I think you should close this and pursue #79

**Comment by anandology** [comment]
Yes, we'll implement that as part of #79.
