### ISSUE TITLE
Move graphs to separate page

### ISSUE THREAD

**Issue by anandology** [anandology/cleansweep#65]
All the stats/graphs are currently being shown one the main page of a place. I think it'll be better to have a separate page for them.

**Comment by devilankur18** [comment]
working on it

**Comment by devilankur18** [comment]
@anandology Send the pull request request #68 please review

**Comment by devilankur18** [comment]
@anandology please close the issue if ok

**Comment by anandology** [comment]
Fixed by PR #68.
