### ISSUE TITLE
Add Committee Structures for Delhi

### ISSUE THREAD

**Issue by anandology** [anandology/cleansweep#70]
Please find below the structure of Main wing.

    Delhi Convener
    ​Secretary
    Treasurer
    Joint Secretary

    ​District In-charges (14)​
    ​District Secretary ​(14)
    District Treasurer  (14)
    District VP (2 per district)
    ​District Grievance In-charge ​

    ​Assembly Coordinator ​
    ​Assembly secretary ​
    ​Assembly Treasurer​
    ​Assembly Grievance In-charge​

    ​Ward Coordinator
    ​Ward Secretary 
    Ward treasurer
    Ward Grievance In-charge
    Ward Observer

    ​Polling Station In-charge
    Booth In-charge​

**Comment by anandology** [comment]
I'm working on this.

**Comment by anandology** [comment]
@devilankur18 may be you try this.

Basically we need to create 6 different committee structures.

* state-committee
* district-committee
* ac-committee
* ward-committee
* px-committee
* booth-committee

**Comment by devilankur18** [comment]
@anandology I have added all the committees to delhi test site.

**Comment by anandology** [comment]
Thanks @devilankur18 !
