### ISSUE TITLE
Rename "Local Body" to WARD for Delhi

### ISSUE THREAD

**Issue by anandology** [anandology/cleansweep#75]

**Comment by charanjeetaap** [comment]
has this been updated anand sir..?

**Comment by anandology** [comment]
Done on the test website.

**Comment by anandology** [comment]
Keeping the issue open as we'll have to handle that in the cleansweep-data repo as well so that new installations get the name as WARD.

**Comment by charanjeetaap** [comment]
don't do all capitals, keep it as "Ward"

**Comment by anandology** [comment]
We use abbreviations like AC, PB for Assembly Constituency, Polling Booth etc. But for small names like State and Ward, we are just using the same name in caps. 

I think we can live with it for now. Marking the issue as closed.
