### ISSUE TITLE
upload the volunteer data

### ISSUE THREAD

**Issue by charanjeetaap** [anandology/cleansweep#78]
need a functionality to upload the volunteer data through an excel file...applying all the contraints that are there in the volunteer entry form..

**Comment by charanjeetaap** [comment]
pls take this on priority for now, as we need this to start using the system

**Comment by anandology** [comment]
This can be done from Contacts -> Add New Contacts -> Add Volunteers. It is possible to copy & paste columns from Excel to this. 

Good enough to get data loaded into the system. Closing it for now.
